"""add_document_chunk_fields

Revision ID: 02f19541ffe2
Revises: aeab5e01f619
Create Date: 2026-06-29 04:13:40.708034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f19541ffe2'
down_revision: Union[str, Sequence[str], None] = 'aeab5e01f619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('document_id', sa.String(length=36), nullable=False))
    op.add_column('document_chunks', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.add_column('document_chunks', sa.Column('character_count', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_offset', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'end_offset')
    op.drop_column('document_chunks', 'start_offset')
    op.drop_column('document_chunks', 'character_count')
    op.drop_column('document_chunks', 'chunk_text')
    op.drop_column('document_chunks', 'document_id')
    # ### end Alembic commands ###
