"""add_document_fields

Revision ID: 1a663a4c8897
Revises: a89efe65c1dd
Create Date: 2026-06-28 15:35:26.103216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a663a4c8897'
down_revision: Union[str, Sequence[str], None] = 'a89efe65c1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('uploader_id', sa.String(length=36), nullable=False))
    op.add_column('documents', sa.Column('organization_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['uploader_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'organization_id')
    op.drop_column('documents', 'uploader_id')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'stored_path')
    # ### end Alembic commands ###
