"""add_chromadb_indexing_fields_to_document_chunk

Revision ID: 1b71320edcb0
Revises: 7e331acfaf96
Create Date: 2026-06-29 06:04:48.426100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b71320edcb0'
down_revision: Union[str, Sequence[str], None] = '7e331acfaf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('indexed_status', sa.String(length=50), server_default='Pending', nullable=False))
    op.add_column('document_chunks', sa.Column('indexed_at', sa.DateTime(), nullable=True))
    op.add_column('document_chunks', sa.Column('vector_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'vector_id')
    op.drop_column('document_chunks', 'indexed_at')
    op.drop_column('document_chunks', 'indexed_status')
    # ### end Alembic commands ###
