"""add_embedding_fields_to_document_chunk

Revision ID: 7e331acfaf96
Revises: 02f19541ffe2
Create Date: 2026-06-29 05:49:29.054420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e331acfaf96'
down_revision: Union[str, Sequence[str], None] = '02f19541ffe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_status', sa.String(length=50), server_default='Pending', nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('embedded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedded_at')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'embedding_status')
    # ### end Alembic commands ###
