"""Add feedback metadata columns

Revision ID: c6cb32cb45e3
Revises: d0cfdaeb5097
Create Date: 2026-06-29 13:40:11.428220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cb32cb45e3'
down_revision: Union[str, Sequence[str], None] = 'd0cfdaeb5097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('feedbacks', sa.Column('organization_id', sa.String(length=36), nullable=False))
    op.add_column('feedbacks', sa.Column('rating', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'feedbacks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedbacks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'rating')
    op.drop_column('feedbacks', 'organization_id')
    op.drop_column('feedbacks', 'user_id')
    # ### end Alembic commands ###
