"""Add session delete and message role and verification

Revision ID: d0cfdaeb5097
Revises: 1b71320edcb0
Create Date: 2026-06-29 13:36:48.146077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cfdaeb5097'
down_revision: Union[str, Sequence[str], None] = '1b71320edcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('verification', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'verification')
    op.drop_column('messages', 'role')
    op.drop_column('chat_sessions', 'is_deleted')
    # ### end Alembic commands ###
